# Generated by Django 3.2.6 on 2021-08-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user1',
            new_name='user',
        ),
    ]
