# Generated by Django 3.2.6 on 2021-08-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_user1_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datacompleted',
            new_name='datecompleted',
        ),
    ]
